apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
  annotations:
    description: |
      A task run tests with different combinations of platforms and browsers
spec:
  params:
    - name: outputs
      type: array
  steps:
    - name: echo
      image: alpine
      script: |
        echo "running tests on $(params.outputs)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: matrixed-pr-
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: produce-platforms-and-browsers
        matrix:
          params:
            - name: platform
              value:
                - linux
                - mac
                - windows
            - name: browser
              value:
                - chrome
                - safari
                - firefox
        taskSpec:
          params:
            - name: platform
              type: string
            - name: browser
              type: string
          results:
            - name: output
              type: string
          steps:
            - name: echo
              image: alpine
              script: |
                echo "$(params.platform)-$(params.browser)"
      - name: platforms-and-browsers-dag
        matrix:
          params:
            - name: outputs
              value:
                - $(tasks.produce-platforms-and-browsers.results.output[0])
                - $(tasks.produce-platforms-and-browsers.results.output[1])
                - $(tasks.produce-platforms-and-browsers.results.output[2])
        taskRef:
          name: run-tests
