apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: matrixed-pr-
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: produce-platforms-and-browsers
        matrix:
          params:
            - name: platform
              value:
                - linux
                - mac
                - windows
            - name: browser
              value:
                - chrome
                - safari
                - firefox
        taskSpec:
          params:
            - name: platform
              type: string
            - name: browser
              type: string
          results:
            - name: report-url
              type: string
          steps:
            - name: echo
              image: alpine
              script: |
                echo "https://api.example/get-report/$(params.platform)-$(params.browser)"
      - name: fetch-linux-reports
        params:
          - name: report-url
            value:
              - $(tasks.produce-platforms-and-browsers.results.report-url[0])
              - $(tasks.produce-platforms-and-browsers.results.report-url[1])
              - $(tasks.produce-platforms-and-browsers.results.report-url[2])
        taskSpec:
        steps:
          - name: echo
            image: alpine
            script: |
              ...
              echo "fetching report: $(results.report-url)"
