apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: platforms-task
  annotations:
    description: |
      A task that does something cool with platforms
spec:
  params:
    - name: platform
  steps:
    - name: echo
      image: alpine
      script: |
        echo "$(params.platform)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: matrixed-pr-
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: get-platforms
        taskSpec:
          results:
            - name: platforms
              type: array
          steps:
            - name: produce-a-list-of-platforms
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo -n "[\"linux\",\"mac\",\"windows\"]" | tee $(results.platforms.path)
      - name: platforms-and-browsers-dag
        matrix:
          params:
            - name: platform
              value: $(tasks.get-platforms.results.platforms[*])
        taskRef:
          name: platforms-task
