apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: arraytask
spec:
  params:
    - name: DIGEST
      type: array
  steps:
    - name: echo
      image: alpine
      script: |
        echo "$(params.DIGEST[0])"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stringtask
spec:
  params:
    - name: DIGEST
      type: string
  steps:
    - name: echo
      image: alpine
      script: |
        echo "deploying image: $(params.DIGEST)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: matrix-emitting-results
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: matrix-emitting-results
        matrix:
          include:
            - name: build-1
              params:
                - name: IMAGE
                  value: image-1
                - name: DOCKERFILE
                  value: path/to/Dockerfile1
            - name: build-2
              params:
                - name: IMAGE
                  value: image-2
                - name: DOCKERFILE
                  value: path/to/Dockerfile2
            - name: build-3
              params:
                - name: IMAGE
                  value: image-3
                - name: DOCKERFILE
                  value: path/to/Dockerfile3
        taskSpec:
          params:
            - name: IMAGE
            - name: DIGEST
              default: ""
          results:
            - name: IMAGE-DIGEST
          steps:
            - name: produce-image-digest
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo "Building image for $(params.IMAGE)"
                echo -n "$(params.DIGEST)" | sha256sum | tee $(results.IMAGE-DIGEST.path)
      - name: task-deploy-images
        params:
          - name: DIGEST
            value: $(tasks.matrix-emitting-results.results.IMAGE-DIGEST[*])
        taskSpec:
          params:
            - name: DIGEST
              type: array
          steps:
            - name: echo
              image: alpine
              script: |
                echo "deploying image: $(params.DIGEST[0])"
      - name: matrixed-task-deploy-images
        matrix:
          params:
            - name: DIGEST
              value: $(tasks.matrix-emitting-results.results.IMAGE-DIGEST[*])
        taskSpec:
          params:
            - name: DIGEST
              type: string
          steps:
            - name: echo
              image: alpine
              script: |
                echo "deploying image: $(params.DIGEST)"
