apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: platforms-with-results
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: matrix-emitting-results
        matrix:
          params:
            - name: platform
              value:
                - linux
                - mac
                - windows
            - name: browser
              value:
                - chrome
                - safari
                - firefox
        taskSpec:
          params:
            - name: platform
              default: ""
            - name: browser
              default: ""
          results:
            - name: report-url
              type: string
          steps:
            - name: produce-report-url
              image: alpine
              script: |
                echo "Running tests on $(params.platform)-$(params.browser)"
                echo -n "https://api.example/get-report/$(params.platform)-$(params.browser)" | tee $(results.report-url.path)
      - name: task-consuming-results
        params:
          - name: url
            value:
              - $(tasks.matrix-emitting-results.results.report-url[0])
              - $(tasks.matrix-emitting-results.results.report-url[1])
              - $(tasks.matrix-emitting-results.results.report-url[2])
        taskSpec:
          params:
            - name: url
              type: array
          steps:
            - name: use-environments
              image: bash:latest
              args: ["$(params.url[*])"]
              script: |
                for arg in "$@"; do
                  echo "Arg: $arg"
                done
